[database-setup] initial migrate 作成完了
sanmyathida01/6g_cherry_team_server pull request #2
Opened 2021-10-17 14:06 UTC by hninhninyu2

## やったこと

-   database migration setup

## やらないこと

-   無し

## できるようになること（ユーザ目線）

-   無し

## できなくなること（ユーザ目線）

-   無し

## 動作確認

-    migration setup して実装しました。

## その他

-   特に無し

2021-10-23 09:22 UTC, cherryzaw reviewed
①全テーブル：論理名をコメントしてください。
②下記のデータ型ですが、4 Bytesでお願いします。
mst_teams_categories.teams_categories_id
tb_login_users.login_users_id
tb_organizations.id

③PKとFKのデータ型が一致していない。
PK:
tb_login_users.login_users_id bigint(20) unsigned auto_increment
FK:
alltable.created_user_id int(11)
alltable.updated_user_id int(11)
tb_posts.from_user_id int(10) unsigned
tb_posts.to_user_id int(10) unsigned

PK:
mst_teams_categories.teams_categories_id bigint(20) unsigned auto_increment
FK:
tb_posts.team_categories_id int(11)

④text又はvarchar(max)でお願いします。
tb_posts.content varchar(50)

2021-11-02 13:41 UTC, cherryzaw commented on database/migrations/2021_10_17_103558_create_mst_login_user_roles_table.php
> +            $table->integer('created_user_id')->nullable()->comment('作成者');
$table->unsignedInteger('created_user_id')->nullable()->comment('作成者');

2021-11-02 13:43 UTC, cherryzaw commented on database/migrations/2021_10_17_103558_create_mst_login_user_roles_table.php
> +            $table->integer('updated_user_id')->nullable()->comment('更新者');
@hninhninyu2 
$table->unsignedInteger('updated_user_id')->nullable()->comment('更新者');

2021-11-02 13:50 UTC, cherryzaw commented on php-fpm/php.ini
> +memory_limit = 256M
memory_limit = -1

2021-11-02 13:58 UTC, cherryzaw reviewed
@hninhninyu2 
すべての対象ファイルにて
$table->integer('created_user_id')->nullable()->comment('作成者');
$table->integer('updated_user_id')->nullable()->comment('更新者');
 ↓
$table->unsignedInteger('created_user_id')->nullable()->comment('作成者');
$table->unsignedInteger('updated_user_id')->nullable()->comment('更新者');

php.ini設定
memory_limit = -1

Dockerfileの設定
’## Install php libraries.
RUN composer install

2021-11-02 14:30 UTC, cherryzaw approved these changes

2021-11-02 14:32 UTC, cherryzaw commented
Review OK

2021-11-02 14:32 UTC, cherryzaw commented
Review OK

2021-11-09 11:59 UTC, sanmyathida01 requested changes
LGTM

2021-11-09 11:59 UTC, merged